# Develop override settings
# to use locally: `jekyll serve --config _config.yml,_config.dev.yml`

environment         : "dev"
site_debug          : true
url                 : http://localhost:4000
analytics:
  provider          : false
comments:
  disqus:
    shortname       : "denali-dev"
sass:
  style             : expanded
