# Site Settings
environment              : "prod"
locale                   : "en-US"
title                    : "Denali Documentation Site"
title_separator          : "-"
title_brand              : "Denali"
name                     : &name "Denali Team" # &name is a YAML anchor which can be *referenced later
description              : &description "Documentation for the Denali styleguide"
url                      : https://denali.design # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : denali-design/denali-styleguide
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook               : # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification : # Replace this with your ID, or delete
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google                 :
    tracking_id          : # Replace this with your ID, or delete

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : ""
  bio              : ""
  location         : ""
  email            :
  uri              : ""
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : 
  foursquare       :
  github           : "denali-design"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
#highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  #syntax_highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  principles:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: container
      author_profile: true
  # _docs
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: framed-space
      read_time: false
      author_profile: false
      share: false
      comments: false
      section: "docs"
      nav: "docs"
      gitcontent: true
  # _principles
  - scope:
      path: "_principles"
      type: principles
    values:
      layout: framed-space
      read_time: false
      author_profile: false
      share: false
      comments: false
      section: "principles"
      nav: "docs"
      gitcontent: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-sass-converter
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
